export const THESIS_MANIFEST = [
  { id: '01', slug: 'the-gap', title: 'The Gap', summary: 'African culture has global attention, while value does not always return with it.', lens: 'Context', readingMinutes: 3, mapClaimIds: ['african-cultural-attention', 'african-value-gap'], publicCitationIds: [], updatedAt: '2026-07-21' },
  { id: '02', slug: 'the-trap', title: 'The Trap', summary: 'A following is rented when someone else controls the relationship behind it.', lens: 'Diagnosis', readingMinutes: 3, mapClaimIds: ['attract-then-extract', 'rented-audience-relationship'], publicCitationIds: [], updatedAt: '2026-07-21' },
  { id: '03', slug: 'the-unlock', title: 'The Unlock', summary: 'Open rails can help people carry payments, access, and participation forward.', lens: 'Mechanism', readingMinutes: 3, mapClaimIds: ['open-economic-rails'], publicCitationIds: [], updatedAt: '2026-07-21' },
  { id: '04', slug: 'the-thesis', title: 'The Thesis', summary: 'Attention can lead to participation, ownership, and value that stays closer.', lens: 'Mission', readingMinutes: 3, mapClaimIds: ['attention-to-ownership'], publicCitationIds: [], updatedAt: '2026-07-21' },
  { id: '05', slug: 'the-company', title: 'The Company', summary: 'Chainfren builds infrastructure for attention and ownership.', lens: 'Mission', readingMinutes: 3, mapClaimIds: ['chainfren-mission'], publicCitationIds: [], updatedAt: '2026-07-21' },
  { id: '06', slug: 'what-we-build', title: 'What We Build', summary: 'Public products make owned audience relationships practical.', lens: 'Execution', readingMinutes: 4, mapClaimIds: ['sabi-attention', 'creator-network-distribution', 'products-owned-infrastructure'], publicCitationIds: [], updatedAt: '2026-07-21' },
  { id: '07', slug: 'how-we-work', title: 'How We Work', summary: 'We connect culture, product craft, and accountable participation.', lens: 'Practice', readingMinutes: 3, mapClaimIds: [], publicCitationIds: [], updatedAt: '2026-07-21' },
  { id: '08', slug: 'the-road-ahead', title: 'The Road Ahead', summary: 'Future work tests how participation can become shared value.', lens: 'Horizon', readingMinutes: 3, mapClaimIds: ['star-factor-proof', 'owned-value-outcome'], publicCitationIds: [], updatedAt: '2026-07-21' },
  { id: '09', slug: 'build-with-us', title: 'Build With Us', summary: 'Creators, partners, and supporters can help shape the work.', lens: 'Invitation', readingMinutes: 2, mapClaimIds: [], publicCitationIds: [], updatedAt: '2026-07-21' },
]
