export const THESIS_MANIFEST = [
  { id: '01', slug: 'the-gap', title: 'The Gap', summary: 'Africans create attention, while control and value too often collect elsewhere.', lens: 'Context', readingMinutes: 3, mapClaimIds: ['african-attention-value', 'african-value-gap'], publicCitationIds: [], updatedAt: '2026-08-25' },
  { id: '02', slug: 'the-trap', title: 'The Trap', summary: 'Extractive systems turn real communities into rented relationships.', lens: 'Diagnosis', readingMinutes: 3, mapClaimIds: ['extractive-systems', 'rented-relationships'], publicCitationIds: [], updatedAt: '2026-08-25' },
  { id: '03', slug: 'the-unlock', title: 'The Unlock', summary: 'Blockchain can provide practical open rails for identity, payment, settlement, and participation.', lens: 'Mechanism', readingMinutes: 3, mapClaimIds: ['blockchain-open-rails'], publicCitationIds: [], updatedAt: '2026-08-25' },
  { id: '04', slug: 'the-thesis', title: 'The Thesis', summary: 'Attention can become participation, ownership, and value that stays closer to Africans.', lens: 'Mission', readingMinutes: 3, mapClaimIds: ['attention-to-participation', 'participation-to-ownership', 'ownership-to-value'], publicCitationIds: [], updatedAt: '2026-08-25' },
  { id: '05', slug: 'the-company', title: 'The Company', summary: 'Chainfren pursues its mission through a distribution-first company.', lens: 'Mission', readingMinutes: 3, mapClaimIds: ['distribution-first', 'chainfren-mission'], publicCitationIds: [], updatedAt: '2026-08-25' },
  { id: '06', slug: 'what-we-build', title: 'What We Build', summary: 'TiVi is the flagship expression within a focused public product system.', lens: 'Execution', readingMinutes: 4, mapClaimIds: ['tivi-flagship'], publicCitationIds: [], updatedAt: '2026-08-25' },
  { id: '07', slug: 'how-we-work', title: 'How We Work', summary: 'African context, voluntary participation, portability, and the right to leave guide the work.', lens: 'Practice', readingMinutes: 3, mapClaimIds: [], publicCitationIds: [], updatedAt: '2026-08-25' },
  { id: '08', slug: 'the-road-ahead', title: 'The Road Ahead', summary: 'The ambition is an African-built open ecosystem for distribution, ownership, and value.', lens: 'Horizon', readingMinutes: 3, mapClaimIds: ['african-built-ecosystem'], publicCitationIds: [], updatedAt: '2026-08-25' },
  { id: '09', slug: 'build-with-us', title: 'Build With Us', summary: 'Everyone who can strengthen the mission shares one invitation to take part.', lens: 'Invitation', readingMinutes: 2, mapClaimIds: [], publicCitationIds: [], updatedAt: '2026-08-25' },
]
